// AUTH
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const AUTHENTICATE = 'AUTHENTICATE';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
// API CALLS
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const CLEAN_UP = 'CLEAN_UP';

//PRODUCT CALLS
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';

//NETWORK CALLS
export const NETWORK_CALL_START = 'NETWORK_CALL_START';
export const NETWORK_CALL_REFRESH = 'NETWORK_CALL_REFRESH';
export const NETWORK_CALL_ERROR = 'NETWORK_CALL_ERROR';
